jobs:
  include: #frontend tests, node_js
    - language: node_js
      node_js:
        - node
        - lts/*
      cache:
      directories:
        - ~/.npm
      before_script:
        - cd homepairs/homepairsUI
        - npm install -g npm@latest
      script:
        - npm ci
        - npx jest --ci

  #backend tests, python
    - language: python
      python:
        - "3.7.4"
      services:
        - postgresql
      env:
        - DJANGO=3.0.2 DB=postgresql
      install:
        - cd homepairs/HomepairsApp
        - ./travisScripts/installScript.sh
      before_script:
        - ./travisScripts/beforeTests.sh     
      script:
        - ./travisScripts/runDBTests.sh
